# Config file for ./flutterw analyze

# flutter_lints adds default config for Flutter projects
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    # Do not analyze generated files
    - '**/*.mocks.dart'
    - '**/*.g.dart'
    - '**/*.gen.dart'
    - '**/*.freezed.dart'
  errors:
    # See also https://dart.dev/tools/diagnostic-messages#diagnostics
    missing_required_param: error
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    # See also https://dart-lang.github.io/linter/lints/
    - always_use_package_imports
    - prefer_single_quotes