name: mesh
description: "nRF Bluetooth Mesh demo"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  nordic_nrf_mesh: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/files/